"""add directory fields to businesses

Revision ID: 5c8e2191a699
Revises: eb1d5d2b97dc
Create Date: 2026-09-16 23:58:59.888071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c8e2191a699'
down_revision: Union[str, Sequence[str], None] = 'eb1d5d2b97dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # HAND-ADDED. Autogenerate does not emit this, and the migration fails without it:
    #   psycopg.errors.UndefinedObject: type "business_category" does not exist
    #
    # `create_table` creates the enum types its columns use; `add_column` does not. The
    # type has to exist before a column can be declared with it, so it is created here
    # explicitly. checkfirst=True keeps the migration re-runnable.
    business_category = sa.Enum(
        'barber', 'salon', 'clinic', 'dentist', 'tutor', 'fitness', 'other',
        name='business_category',
    )
    business_category.create(op.get_bind(), checkfirst=True)

    op.add_column('businesses', sa.Column('category', business_category, server_default='other', nullable=False))
    op.add_column('businesses', sa.Column('city', sa.String(length=80), nullable=True))
    op.add_column('businesses', sa.Column('image_url', sa.Text(), nullable=True))
    op.add_column('businesses', sa.Column('is_listed', sa.Boolean(), server_default='true', nullable=False))
    op.create_index(op.f('ix_businesses_category'), 'businesses', ['category'], unique=False)
    op.create_index(op.f('ix_businesses_city'), 'businesses', ['city'], unique=False)
    op.create_index(op.f('ix_businesses_is_listed'), 'businesses', ['is_listed'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_businesses_is_listed'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_city'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_category'), table_name='businesses')
    op.drop_column('businesses', 'is_listed')
    op.drop_column('businesses', 'image_url')
    op.drop_column('businesses', 'city')
    op.drop_column('businesses', 'category')
    # ### end Alembic commands ###

    # HAND-ADDED, same reason as the initial migration: drop_column removes the column
    # but leaves the PostgreSQL ENUM type behind, so re-running the upgrade would fail
    # with "type business_category already exists".
    sa.Enum(name="business_category").drop(op.get_bind(), checkfirst=True)
