"""add reminder_sent_at to bookings

Revision ID: eb1d5d2b97dc
Revises: c79634e2463a
Create Date: 2026-09-16 22:19:32.351472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb1d5d2b97dc'
down_revision: Union[str, Sequence[str], None] = 'c79634e2463a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('reminder_sent_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'reminder_sent_at')
    # ### end Alembic commands ###
